name: manual-demo

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        required: false
  repository_dispatch:
    types: [run-tests, clear-cache]  # nómbralos como quieras

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs (workflow_dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "LogLevel=${{ github.event.inputs.logLevel }}"
          echo "Tags=${{ github.event.inputs.tags }}"
      - name: Echo payload (repository_dispatch)
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "Action=${{ github.event.action }}"
          echo 'Payload:'
          echo '${{ toJson(github.event.client_payload) }}'
