name: Secrets Precedence Demo

on:
  push:
    branches: [main]
  workflow_dispatch:  # ← Permite ejecutar manualmente desde GitHub UI

jobs:
  # Job SIN environment - usa Repository Secret
  test-without-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Show API Key (No Environment)
        run: |
          echo "Job: test-without-environment"
          echo "API_KEY length: ${#API_KEY}"
          echo "API_KEY first 3 chars: ${API_KEY:0:3}"
          echo "Expected: repository secret (length ~25, starts 'rep')"
          echo "---"
        env:
          API_KEY: ${{ secrets.API_KEY }}
      
      - name: Identify which secret is being used
        run: |
          SECRET_HASH=$(echo "${{ secrets.API_KEY }}" | sha256sum | cut -c1-8)
          echo "Secret hash: $SECRET_HASH"
          echo "If hash matches your known values:"
          echo "- Organization secret = [calculate hash of your org secret]"
          echo "- Repository secret = [calculate hash of your repo secret]"
          
      - name: Show which secret is being used
        run: |
          echo "First 4 characters: ${API_KEY:0:4}"
          if [[ "$API_KEY" == ORG-* ]]; then
            echo "✅ Using ORGANIZATION secret"
          elif [[ "$API_KEY" == REPO-* ]]; then
            echo "✅ Using REPOSITORY secret" 
          elif [[ "$API_KEY" == ENV-* ]]; then
            echo "✅ Using ENVIRONMENT secret"
          fi
        env:
          API_KEY: ${{ secrets.API_KEY }}

  # Job CON environment - usa Environment Secret  
  test-with-environment:
    runs-on: ubuntu-latest
    environment: production  # ← Esto activa el environment secret
    steps:
      - name: Show API Key (With Environment)
        run: |
          echo "Job: test-with-environment"
          echo "Environment: production"
          echo "API_KEY length: ${#API_KEY}"
          echo "API_KEY first 3 chars: ${API_KEY:0:3}"
          echo "Expected: environment secret (length ~25, starts 'env')"
          echo "---"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          
      - name: Identify which secret (production environment)
        run: |
          SECRET_HASH=$(echo "${{ secrets.API_KEY }}" | sha256sum | cut -c1-8)
          echo "Production environment - Secret hash: $SECRET_HASH"
          
      - name: Show which secret is being used (production)
        run: |
          echo "First 4 characters: ${API_KEY:0:4}"
          if [[ "$API_KEY" == ORG-* ]]; then
            echo "✅ Using ORGANIZATION secret"
          elif [[ "$API_KEY" == REPO-* ]]; then
            echo "✅ Using REPOSITORY secret" 
          elif [[ "$API_KEY" == ENV-* ]]; then
            echo "✅ Using ENVIRONMENT secret"
          fi
        env:
          API_KEY: ${{ secrets.API_KEY }}

  # Job CON environment diferente (sin secret) - usa Repository Secret
  test-staging-environment:
    runs-on: ubuntu-latest
    environment: staging  # Environment que NO tiene API_KEY definido
    steps:
      - name: Show API Key (Staging Environment)
        run: |
          echo "Job: test-staging-environment"
          echo "Environment: staging (no API_KEY defined)"
          echo "API_KEY length: ${#API_KEY}"
          echo "API_KEY first 3 chars: ${API_KEY:0:3}"
          echo "Expected: repository secret (length ~25, starts 'rep')"
          echo "---"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          
      - name: Show which secret is being used (staging)
        run: |
          echo "First 4 characters: ${API_KEY:0:4}"
          if [[ "$API_KEY" == ORG-* ]]; then
            echo "✅ Using ORGANIZATION secret"
          elif [[ "$API_KEY" == REPO-* ]]; then
            echo "✅ Using REPOSITORY secret" 
          elif [[ "$API_KEY" == ENV-* ]]; then
            echo "✅ Using ENVIRONMENT secret"
          fi
        env:
          API_KEY: ${{ secrets.API_KEY }}

  # Simulación si NO existiera Repository Secret
  simulate-organization-only:
    runs-on: ubuntu-latest
    steps:
      - name: Show what happens with only Organization Secret
        run: |
          echo "Job: simulate-organization-only"
          echo "Si SOLO existiera Organization Secret:"
          echo "API_KEY value would be: organization-api-key-12345"
          echo "But actual value: ${{ secrets.API_KEY }}"
          echo "Expected: repository-api-key-67890 (because repo secret exists)"
