name: Secrets Precedence Demo

on:
  push:
    branches: [main]
  workflow_dispatch:  # ← Permite ejecutar manualmente desde GitHub UI

jobs:
  # Job SIN environment - usa Repository Secret
  test-without-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Show API Key (No Environment)
        run: |
          echo "Job: test-without-environment"
          echo "API_KEY value: ${{ secrets.API_KEY }}"
          echo "Expected: repository-api-key-67890"
          echo "---"

  # Job CON environment - usa Environment Secret  
  test-with-environment:
    runs-on: ubuntu-latest
    environment: production  # ← Esto activa el environment secret
    steps:
      - name: Show API Key (With Environment)
        run: |
          echo "Job: test-with-environment"
          echo "Environment: production"
          echo "API_KEY value: ${{ secrets.API_KEY }}"
          echo "Expected: environment-api-key-abcde"
          echo "---"

  # Job CON environment diferente (sin secret) - usa Repository Secret
  test-staging-environment:
    runs-on: ubuntu-latest
    environment: staging  # Environment que NO tiene API_KEY definido
    steps:
      - name: Show API Key (Staging Environment)
        run: |
          echo "Job: test-staging-environment"
          echo "Environment: staging (no API_KEY defined)"
          echo "API_KEY value: ${{ secrets.API_KEY }}"
          echo "Expected: repository-api-key-67890"
          echo "---"

  # Simulación si NO existiera Repository Secret
  simulate-organization-only:
    runs-on: ubuntu-latest
    steps:
      - name: Show what happens with only Organization Secret
        run: |
          echo "Job: simulate-organization-only"
          echo "Si SOLO existiera Organization Secret:"
          echo "API_KEY value would be: organization-api-key-12345"
          echo "But actual value: ${{ secrets.API_KEY }}"
          echo "Expected: repository-api-key-67890 (because repo secret exists)"
